### ISSUE TITLE
Invalid channel id

### ISSUE THREAD

**Issue by negadmin** [forcedotcom/EMP-Connector#78]
Hello,

I am following the [Salesforce Trailhead to subscribe to Change Data Capture Event Channel using EMP-Connector](https://trailhead.salesforce.com/content/learn/modules/change-data-capture/subscribe-to-events). I run the following command in GIT bash but always get the error below. I have tried researching a solution but had not luck. Could anyone provide some direction?

**Command run against a Handson Org**
java -jar target/emp-connector-0.0.1-SNAPSHOT-phat.jar <username> <password> /data/AccountChangeEvent

**Error**
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IllegalArgumentException: Invalid channel id: C:/tools/Git/data/AccountChangeEvent
        at org.cometd.bayeux.ChannelId.<init>(ChannelId.java:57)
        at org.cometd.client.BayeuxClient.newChannelId(BayeuxClient.java:460)
        at org.cometd.common.AbstractClientSession.getChannel(AbstractClientSession.java:140)
        at org.cometd.common.AbstractClientSession.getChannel(AbstractClientSession.java:126)
        at com.salesforce.emp.connector.EmpConnector$SubscriptionImpl.subscribe(EmpConnector.java:87)
        at com.salesforce.emp.connector.EmpConnector.subscribe(EmpConnector.java:212)
        at com.salesforce.emp.connector.example.LoginExample.main(LoginExample.java:59)

Thanks for any help,
Neil

**Comment by baslu93** [comment]
Git bash try to prepend the Git folder path, try with another cli tool

**Comment by baslu93** [comment]
Hi Neil,

Git bash try to prepend the Git folder path, try with another cli tool.
I've tried with CMD and it works for me.

Luca
