### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by COUTURIEREtienne** [forcedotcom/EMP-Connector#94]
So i'm following this trailhead https://trailhead.salesforce.com/content/learn/modules/change-data-capture/subscribe-to-events?trail_id=architect-solutions-with-the-right-api and when i need to use this command :
java -jar target/emp-connector-0.0.1-SNAPSHOT-phat.jar orgName orgPassword /data/Employee__ChangeEvent
I keep getting this error 

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NumberFormatException: For input string: "/data/Employee__ChangeEvent"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Long.parseLong(Long.java:678)
        at java.base/java.lang.Long.parseLong(Long.java:817)
        at com.salesforce.emp.connector.example.LoginExample.main(LoginExample.java:43)

**Comment by COUTURIEREtienne** [comment]
So i managed to find the solution, the command "$ java -jar target/emp-connector-0.0.1-SNAPSHOT-phat.jar <username> <password> /data/Employee__ChangeEvent" must have your password and the security token all attached
