### ISSUE TITLE
TimeoutException in thread main and failure to connect to meta/handshake

### ISSUE THREAD

**Issue by vanlanjr** [forcedotcom/EMP-Connector#99]
I am facing an issue where I am trying to subscribe to custom events using bearer tokens but I am getting a TimeoutException as soon as I run the command given for the BearerTokenExample.

Here is the output:
41 [main] INFO org.eclipse.jetty.util.log - Logging initialized @167ms to org.eclipse.jetty.util.log.Slf4jLog
68 [main] INFO com.salesforce.emp.connector.EmpConnector - EmpConnector connecting
Exception in thread "main" java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
        at com.salesforce.emp.connector.example.BearerTokenExample.main(BearerTokenExample.java:66)
>>>>
[2022-09-20 11:00:30.048] Failure:[/meta/handshake]
{failure={exception=java.util.concurrent.TimeoutException: Total timeout 15000 ms elapsed, message={ext={replay=true}, supportedConnectionTypes=[long-polling], channel=/meta/handshake, id=1, version=1.0}, connectionType=long-polling}, channel=/meta/handshake, id=1, successful=false}
<<<<
>>>>
[2022-09-20 11:00:45.066] Failure:[/meta/handshake]
{failure={exception=java.util.concurrent.TimeoutException: Total timeout 15000 ms elapsed, message={ext={replay=true}, supportedConnectionTypes=[long-polling], channel=/meta/handshake, id=2, version=1.0}, connectionType=long-polling}, channel=/meta/handshake, id=2, successful=false}
<<<<

Any idea why this is happening?

**Comment by cyachana** [comment]
Hi, I am facing the exact same issue. Were you able to find any solution to this? Thanks.
